### PR TITLE
Update README.md for Minio.io Settings

### PR DESCRIPTION
**Pull request by Frostist**
Added Minio.io Documentation as per my issue report. https://github.com/catalyst/moodle-tool_objectfs/issues/579

### CODE REVIEW

**Comment by Frostist** [comment]
As per my conversation found https://github.com/catalyst/moodle-tool_objectfs/issues/579
 and https://github.com/catalyst/moodle-tool_objectfs/issues/374

I wanted to update the community to the fact they can use a 3rd party service like Min.io for a open source S3 bucket service.

**Comment by danmarsden** [comment]
Thanks for the PR!

I think before we approve this we should make it clearer in the readme what is "supported" vs what has been "tested as working"

Catalyst doesn't really "support" digital ocean or Min.io - we'd rely on community support for testing/fixing issues with using those.

@brendanheywood - that make sense to you too?

**Comment by Frostist** [comment]
That's fair enough, I just thought it would be nice for users to see they can setup their own minio.io server and DYI the s3 storage instead of going the AWS or Google route.

Thanks!

**Comment by danmarsden** [comment]
yeah I think it makes sense to add the details to the readme, I just don't like the title in the readme that suggests "we" support it directly - along with some other options that I don't think we really "support" ourselves.

**Comment by Frostist** [comment]
Okay! Is there a different section of the readme where I could maybe put it then?

**Comment by danmarsden** [comment]
nah - I think we probably need to adjust the section a bit on our end to make it clearer what "support" means - in particular we offer our code free to download, but don't actively test against all those in the list. I suspect Brendan is the best person to rewrite that section but if he doesn't jump in here I'll see if I can put something together sometime... :-)

**Comment by brendanheywood** [comment]
Yeah and in hindsite I wish we gone with sub plugins so that all these other file stores can be managed by different maintainers in their own repo.

I think maybe have a 'supported' section vs 'community add ons', the first would be the things we personally use in production which is S3, Openstack and Azure but even that it murky as we may not be deploying those for all moodle stables.

**Comment by danmarsden** [comment]
as a first step, I'm going to merge this in and just use github editing tools to update the readme a bit more to make it a little clearer that Catalyst doesn't fully "support" them directly.

**Pull request merged**
