### PR TITLE
S3 compatible

### PR DESCRIPTION
**Pull request by kisonay**
Not sure if this is the best way to accomplish this so if you want any changes done, please let me know.

### CODE REVIEW

**Comment by marcusboon** [comment]
This looks good, however wouldn't it be a better idea to have a separate client that extends the s3_client? I mean I know you say that it mainly uses the S3 functionality, but in the future, if it diverges, it makes it hard to maintain.

**Comment by kisonay** [comment]
That makes sense, do you recommend I extend the s3 client or create an entirely new Digital Ocean Spaces client. I can get this sorted in the next day or two.

**Comment by marcusboon** [comment]
I think create a new dos_client (for instance, call it whatever you want) but then extend the s3_client class to overload the methods that you want changed.

**Comment by kisonay** [comment]
sounds good. Lets go ahead and close this and I will resubmit a clean PR when ready.

**Comment by marcusboon** [comment]
Ok cool, good luck! And thanks for submitting this PR :)

**Comment by kisonay** [comment]
https://github.com/catalyst/moodle-tool_objectfs/pull/130

**Pull request closed without merging**
