### PR TITLE
Issue#109

### PR DESCRIPTION
**Pull request by tuanngocnguyen**

### CODE REVIEW

**Comment by dmitriim** [comment]
@tuanngocnguyen travis is not happy, could you please have a look before merge?

**Comment by tuanngocnguyen** [comment]
@dmitriim It was fine before I make merge request:
https://travis-ci.org/catalyst/moodle-tool_objectfs/builds

**Comment by dmitriim** [comment]
@tuanngocnguyen I know, but if you want me to do a review, please make sure that travis is happy. Thanks. Probably you'd just need to restart failing tasks.

**Comment by tuanngocnguyen** [comment]
Got it, I have restarted the failed jobs.

**Pull request merged**
