### PR TITLE
Moodle 310 stable add commits from master

### PR DESCRIPTION
**Pull request by tuanngocnguyen**
The M310 branch has is_whitelisted function removed as compared to master branch
I have merged the commit from master branch and made changes on Readme file regards supported versions

### CODE REVIEW

**Comment by danmarsden** [comment]
do we even need the MOODLE_310_STABLE branch? - the master branch currently supports 3.4 and higher versions... so under our naming conventions (unless there's a reason to branch) if we want to stop using the "master" named branch, we should create a new MOODLE_34_STABLE branch

**Comment by tuanngocnguyen** [comment]
Hi @danmarsden ,

The M310 applied your suggestion:

https://github.com/catalyst/moodle-tool_objectfs/commit/453c693cbdae82509c92130107e31ea484e47e9b

So I think we need a separate branch for M10+

**Comment by tuanngocnguyen** [comment]
@danmarsden 
Changes in M10: https://github.com/catalyst/moodle-tool_objectfs/blob/MOODLE_310_STABLE/classes/local/manager.php#L245
is_whitelisted has been removed

**Comment by tuanngocnguyen** [comment]
There will be branch for M3.3 cloned from master

**Comment by danmarsden** [comment]
I guess that's a good enough reason as any to create a new branch... :-)

**Comment by brendanheywood** [comment]
@danmarsden for context this work is all about realigning to the new branch name strategy and deprecating master, see:

https://wrms.catalyst.net.nz/wr.php?request_id=383792

**Comment by danmarsden** [comment]
Thanks- was really just a "why 3.10" seems like a weird release to choose as a branching point.

**Pull request merged**
